[package]
name = "esdt-contract-mock"
version = "0.0.0"
authors = ["josh brolin"]
edition = "2018"
publish = false

[lib]
path = "src/esdt_contract_mock.rs"

[dependencies.elrond-wasm]
version = "0.33.0"

[dev-dependencies.elrond-wasm-debug]
version = "0.33.0"
