[package]
name = "royalties-handler-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "dev.man" ]

[dev-dependencies]

[dependencies.royalties-handler]
path = ".."

[dependencies.elrond-wasm-debug]
version = "0.33.0"
