[package]
name = "seller-contract-mock"
version = "0.0.0"
authors = ["dev.man"]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.elrond-wasm]
version = "0.33.0"

[dependencies.esdt-nft-marketplace]
path = "../esdt-nft-marketplace"

[dev-dependencies.elrond-wasm-debug]
version = "0.33.0"
