[package]
name = "nft-collection-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "josh brolin" ]

[dev-dependencies]

[dependencies.nft-collection]
path = ".."

[dependencies.elrond-wasm-debug]
version = "0.33.0"
