[package]
name = "nft-stake"
version = "0.0.0"
authors = ["josh brolin"]
edition = "2018"
publish = false

[lib]
path = "src/endpoints.rs"

[dependencies.elrond-wasm]
version = "0.33.0"

[dev-dependencies.elrond-wasm-debug]
version = "0.33.0"
