[package]
name = "esdt-system-sc-mock-meta"
version = "0.0.0"
authors = ["dev.man"]
edition = "2018"
publish = false

[dependencies.esdt-system-sc-mock]
path = ".."

[dependencies.elrond-wasm-debug]
version = "0.33.0"
