[package]
name = "esdt-nft-marketplace-meta"
version = "0.0.0"
authors = ["dev.man"]
edition = "2018"
publish = false

[dependencies.esdt-nft-marketplace]
path = ".."

[dependencies.elrond-wasm]
version = "0.33.0"

[dependencies.elrond-wasm-debug]
version = "0.33.0"
