[package]
name = "esdt-system-sc-mock"
version = "0.0.0"
authors = ["dev.man"]
edition = "2018"
publish = false

[lib]
path = "src/esdt_system_sc_mock.rs"

[dependencies.elrond-wasm]
version = "0.33.0"

[dev-dependencies.elrond-wasm-debug]
version = "0.33.0"
